- hosts: awx
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_private_key_file: 'secret/awx.pem'
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - ./vars/awx.yml
  tasks:
    - include_role:
        name: conatest_ubuntu_rethinkdb