# ---
# awx_up.yml
#
# Crea una maquina virtual en AWS Lightsail e instala AWX.
# ---
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  vars_files:
    - ./vars/awx.yml
  tasks:
    - include_role:
        name: conatest_lightsail

- hosts: ubuntus
  gather_facts: yes
  become: yes
  vars_files:
    - ./vars/awx.yml
  tasks:
    - include_role:
        name: conatest_profile
    - include_role:
        name: conatest_ubuntu_server_setup
    - include_role:
        name: conatest_ubuntu_docker
    - include_role:
        name: conatest_awx_ubuntu_install
    - include_role:
        name: conatest_nginx_letsencrypt_proxy_pass