# ---
# jupyter_notebook_down.yml
#
# Destruye la instancia de lightsail que corre jupyter_notebook
# ---
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  vars_files:
    - ./vars/jupyter.yml
  tasks:
    - name: Elimina la instancia 'jupyter_notebook'
      block:
        - lightsail:
            state: absent
            region: us-east-1
            name: '{{server_name}}'
      rescue:
        - debug:
            msg: 'Nothing to delete'