- hosts: all
  tasks:
    - name: Install Python 2.7
      apt:
        name: python
        state: present
    - name: Install PIP
      apt:
        name: python-pip
        state: present
    - name: Install docker-py
      pip:
        name: docker-py
        executable: /usr/bin/pip
    - name: Sets the python version to 2.7
      set_fact:
        ansible_python_interpreter: /usr/bin/python
    - name: Run the Rancher Server container image
      docker_container:
        name: rancher
        image: rancher/rancher
        state: started
        ports:
          - '80:80'
          - '443:443'
