- hosts: all
  tasks:
    - lightsail:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        # Create a new Lightsail instance, register the instance details
        state: present
        name: rancher_server
        region: us-east-1
        zone: us-east-1a
        blueprint_id: ubuntu_16_04
        bundle_id: nano_1_0
        key_pair_name: master_key
        wait: yes
        wait_timeout: 5000
      register: server
    - debug:
        msg: '{{ server }}'
    - uri:
        url: http://awx.lightsail.conatest.click/api/v2/authtoken/
        validate_certs: no
        method: POST
        status_code: 200
        body:
          username: '{{awx_host_username}}'
          password: '{{awx_host_password}}'
        body_format: json
        return_content: yes
      register: response
    - debug:
        msg: '{{ response }}'
    - uri:
        url: http://awx.lightsail.conatest.click/api/v2/inventories/6/hosts/
        validate_certs: no
        method: POST
        headers:
          Authorization: 'Token {{response.json.token}}'
        status_code: 201
        body:
          name: '{{server.instance.private_ip_address}}'
          enabled: true
          instance_id: ''
          description: 'Rancher server'
          variables: ''
        body_format: json
