- hosts: all
  tasks:
    - uri:
        url: http://awx.lightsail.conatest.click/api/v2/groups/5/hosts/
        validate_certs: no
        method: GET
        user: '{{awx_host_username}}'
        password: '{{awx_host_password}}'
        status_code:
          - 200
        force_basic_auth: yes
      register: hosts
    - debug:
        msg: '{{ hosts }}'
      with_items: '{{hosts.results | map('from_json') | list}}'
    - uri:
        url: 'http://awx.lightsail.conatest.click{{ item.url }}'
        validate_certs: no
        method: DELETE
        user: '{{awx_host_username}}'
        password: '{{awx_host_password}}'
        status_code:
          - 200
        force_basic_auth: yes
      when: item.description == 'Rancher Server'
      with_items: '{{hosts.results | map('from_json') | list}}'
