- hosts: all
  tasks:
    - lightsail:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        # Create a new Lightsail instance, register the instance details
        state: present
        name: rancher_server
        region: us-east-1
        zone: us-east-1a
        blueprint_id: ubuntu_16_04
        bundle_id: nano_1_0
        key_pair_name: master_key
        wait: yes
        wait_timeout: 5000
