- hosts: all
  tasks:
    - lightsail:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        # Create a new Lightsail instance, register the instance details
        state: present
        name: '{{ item }}'
        region: us-east-1
        zone: us-east-1a
        blueprint_id: ubuntu_16_04
        bundle_id: nano_1_0
        key_pair_name: master_key
        user_data: >
          cat >> /etc/environment <<EOF
          LC_ALL=en_US.UTF-8
          LANG=en_US.UTF-8
          EOF

          cat >> /home/ubuntu/.bashrc << 'EOF'

          # Custom alias
          alias cls="clear"

          # Custom Prompt
          function prompt {
            local BLACK="\[\033[0;30m\]"
            local BLACKBOLD="\[\033[1;30m\]"
            local RED="\[\033[0;31m\]"
            local REDBOLD="\[\033[1;31m\]"
            local GREEN="\[\033[0;32m\]"
            local GREENBOLD="\[\033[1;32m\]"
            local YELLOW="\[\033[0;33m\]"
            local YELLOWBOLD="\[\033[1;33m\]"
            local BLUE="\[\033[0;34m\]"
            local BLUEBOLD="\[\033[1;34m\]"
            local PURPLE="\[\033[0;35m\]"
            local PURPLEBOLD="\[\033[1;35m\]"
            local CYAN="\[\033[0;36m\]"
            local CYANBOLD="\[\033[1;36m\]"
            local WHITE="\[\033[0;37m\]"
            local WHITEBOLD="\[\033[1;37m\]"
            local RESETCOLOR="\[\e[00m\]"

            export PS1="\n$RED\u$PURPLE@$(hostname) $GREEN\w $RESETCOLOR$GREENBOLD\$(git branch 2> /dev/null)\n $BLUE[\#] >>>  $RESETCOLOR"
            export PS2=" | → $RESETCOLOR"
          }

          prompt
          EOF
        wait: yes
        wait_timeout: 5000
      loop:
        - host01
        - host02
        - host03
      register: lightsail

    - debug:
        msg: '{{lightsail}}'

    - debug:
        msg: 'Name: {{ item.instance.name }}'
        loop: '{{lightsail.results}}'

    - debug:
        msg: 'IP is {{ item.networking.private_ip_address }}'
        loop: '{{lightsail.results}}'
