# from galaxy

# Ansible install role
- src: geerlingguy.ansible

# Docker install role
- src: nickjj.docker

# NodeJS install role
- src: geerlingguy.nodejs

# Java install role
- src: geerlingguy.java