- name: Change hostname
  hostname:
    name: '{{server_name}}'
- name: Change hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1'
    line: '127.0.0.1  {{server_name}}'
- name: Fix locale issue
  blockinfile:
    path: /etc/environment
    insertafter: EOF
    content: |
      LC_ALL=en_US.UTF-8
      LANG=en_US.UTF-8