version: '2'
services:
  base:
    build: ./base/
    image: ansible_base
  host01:
    links:
      - base
    build: ./host/
    image: ansible_host
    container_name: host01
    hostname: host01
    command: ['/var/run.sh']
    volumes:
      - ansible_vol:/var/ans
  host02:
    links:
      - base
      - host01
    image: ansible_host
    container_name: host02
    hostname: host02
    command: ['/var/run.sh']
    volumes:
      - ansible_vol:/var/ans
  host03:
    links:
      - base
      - master
      - host02
    image: ansible_host
    container_name: host03
    hostname: host03
    command: ['/var/run.sh']
    volumes:
      - ansible_vol:/var/ans
volumes: ansible_vol:
